openapi: 3.0.0
info:
  title: County APP
  description: A simple application that searches county info by code.
  contact:
    name: Gabriel Albuquerque
    url: https://albuquerque53.github.io/
    email: albuquerque.se@proton.me

  version: '1.0'
servers:
  - url: https://county-app.herokuapp.com
    variables: {}
paths:
  /search/county/{code}:
    get:
      tags:
        - County
      summary: Search County Info
      description: Search county info by county code.
      operationId: SearchCountyInfo
      parameters:
        - name: code
          in: path
          description: County code to search for
          required: true
          style: simple
          schema:
            type: string
            example: SP
      responses:
        '200':
          description: ''
          headers: {}
          content:
            text/plain:
              schema:
                type: string
                example:
                  - name: ALVARAES
                    ibge_code: '1300029'
                  - name: AMATURA
                    ibge_code: '1300060'
                  - name: ANAMA
                    ibge_code: '1300086'
                  - name: ANORI
                    ibge_code: '1300102'
                  - name: APUI
                    ibge_code: '1300144'
                  - name: ATALAIA DO NORTE
                    ibge_code: '1300201'
                  - name: AUTAZES
                    ibge_code: '1300300'
                  - name: BARCELOS
                    ibge_code: '1300409'
                  - name: BARREIRINHA
                    ibge_code: '1300508'
                  - name: BENJAMIN CONSTANT
                    ibge_code: '1300607'
                  - name: BERURI
                    ibge_code: '1300631'
                  - name: BOA VISTA DO RAMOS
                    ibge_code: '1300680'
                  - name: BOCA DO ACRE
                    ibge_code: '1300706'
                  - name: BORBA
                    ibge_code: '1300805'
                  - name: CAAPIRANGA
                    ibge_code: '1300839'
                  - name: CANUTAMA
                    ibge_code: '1300904'
                  - name: CARAUARI
                    ibge_code: '1301001'
                  - name: CAREIRO
                    ibge_code: '1301100'
                  - name: CAREIRO DA VARZEA
                    ibge_code: '1301159'
                  - name: COARI
                    ibge_code: '1301209'
                  - name: CODAJAS
                    ibge_code: '1301308'
                  - name: EIRUNEPE
                    ibge_code: '1301407'
                  - name: ENVIRA
                    ibge_code: '1301506'
                  - name: FONTE BOA
                    ibge_code: '1301605'
                  - name: GUAJARA
                    ibge_code: '1301654'
                  - name: HUMAITA
                    ibge_code: '1301704'
                  - name: IPIXUNA
                    ibge_code: '1301803'
                  - name: IRANDUBA
                    ibge_code: '1301852'
                  - name: ITACOATIARA
                    ibge_code: '1301902'
                  - name: ITAMARATI
                    ibge_code: '1301951'
                  - name: ITAPIRANGA
                    ibge_code: '1302009'
                  - name: JAPURA
                    ibge_code: '1302108'
                  - name: JURUA
                    ibge_code: '1302207'
                  - name: JUTAI
                    ibge_code: '1302306'
                  - name: LABREA
                    ibge_code: '1302405'
                  - name: MANACAPURU
                    ibge_code: '1302504'
                  - name: MANAQUIRI
                    ibge_code: '1302553'
                  - name: MANAUS
                    ibge_code: '1302603'
                  - name: MANICORE
                    ibge_code: '1302702'
                  - name: MARAA
                    ibge_code: '1302801'
                  - name: MAUES
                    ibge_code: '1302900'
                  - name: NHAMUNDA
                    ibge_code: '1303007'
                  - name: NOVA OLINDA DO NORTE
                    ibge_code: '1303106'
                  - name: NOVO AIRAO
                    ibge_code: '1303205'
                  - name: NOVO ARIPUANA
                    ibge_code: '1303304'
                  - name: PARINTINS
                    ibge_code: '1303403'
                  - name: PAUINI
                    ibge_code: '1303502'
                  - name: PRESIDENTE FIGUEIREDO
                    ibge_code: '1303536'
                  - name: RIO PRETO DA EVA
                    ibge_code: '1303569'
                  - name: SANTA ISABEL DO RIO NEGRO
                    ibge_code: '1303601'
                  - name: SANTO ANTONIO DO ICA
                    ibge_code: '1303700'
                  - name: SAO GABRIEL DA CACHOEIRA
                    ibge_code: '1303809'
                  - name: SAO PAULO DE OLIVENCA
                    ibge_code: '1303908'
                  - name: SAO SEBASTIAO DO UATUMA
                    ibge_code: '1303957'
                  - name: SILVES
                    ibge_code: '1304005'
                  - name: TABATINGA
                    ibge_code: '1304062'
                  - name: TAPAUA
                    ibge_code: '1304104'
                  - name: TEFE
                    ibge_code: '1304203'
                  - name: TONANTINS
                    ibge_code: '1304237'
                  - name: UARINI
                    ibge_code: '1304260'
                  - name: URUCARA
                    ibge_code: '1304302'
                  - name: URUCURITUBA
                    ibge_code: '1304401'
              example:
                - name: ALVARAES
                  ibge_code: '1300029'
                - name: AMATURA
                  ibge_code: '1300060'
                - name: ANAMA
                  ibge_code: '1300086'
                - name: ANORI
                  ibge_code: '1300102'
                - name: APUI
                  ibge_code: '1300144'
                - name: ATALAIA DO NORTE
                  ibge_code: '1300201'
                - name: AUTAZES
                  ibge_code: '1300300'
                - name: BARCELOS
                  ibge_code: '1300409'
                - name: BARREIRINHA
                  ibge_code: '1300508'
                - name: BENJAMIN CONSTANT
                  ibge_code: '1300607'
                - name: BERURI
                  ibge_code: '1300631'
                - name: BOA VISTA DO RAMOS
                  ibge_code: '1300680'
                - name: BOCA DO ACRE
                  ibge_code: '1300706'
                - name: BORBA
                  ibge_code: '1300805'
                - name: CAAPIRANGA
                  ibge_code: '1300839'
                - name: CANUTAMA
                  ibge_code: '1300904'
                - name: CARAUARI
                  ibge_code: '1301001'
                - name: CAREIRO
                  ibge_code: '1301100'
                - name: CAREIRO DA VARZEA
                  ibge_code: '1301159'
                - name: COARI
                  ibge_code: '1301209'
                - name: CODAJAS
                  ibge_code: '1301308'
                - name: EIRUNEPE
                  ibge_code: '1301407'
                - name: ENVIRA
                  ibge_code: '1301506'
                - name: FONTE BOA
                  ibge_code: '1301605'
                - name: GUAJARA
                  ibge_code: '1301654'
                - name: HUMAITA
                  ibge_code: '1301704'
                - name: IPIXUNA
                  ibge_code: '1301803'
                - name: IRANDUBA
                  ibge_code: '1301852'
                - name: ITACOATIARA
                  ibge_code: '1301902'
                - name: ITAMARATI
                  ibge_code: '1301951'
                - name: ITAPIRANGA
                  ibge_code: '1302009'
                - name: JAPURA
                  ibge_code: '1302108'
                - name: JURUA
                  ibge_code: '1302207'
                - name: JUTAI
                  ibge_code: '1302306'
                - name: LABREA
                  ibge_code: '1302405'
                - name: MANACAPURU
                  ibge_code: '1302504'
                - name: MANAQUIRI
                  ibge_code: '1302553'
                - name: MANAUS
                  ibge_code: '1302603'
                - name: MANICORE
                  ibge_code: '1302702'
                - name: MARAA
                  ibge_code: '1302801'
                - name: MAUES
                  ibge_code: '1302900'
                - name: NHAMUNDA
                  ibge_code: '1303007'
                - name: NOVA OLINDA DO NORTE
                  ibge_code: '1303106'
                - name: NOVO AIRAO
                  ibge_code: '1303205'
                - name: NOVO ARIPUANA
                  ibge_code: '1303304'
                - name: PARINTINS
                  ibge_code: '1303403'
                - name: PAUINI
                  ibge_code: '1303502'
                - name: PRESIDENTE FIGUEIREDO
                  ibge_code: '1303536'
                - name: RIO PRETO DA EVA
                  ibge_code: '1303569'
                - name: SANTA ISABEL DO RIO NEGRO
                  ibge_code: '1303601'
                - name: SANTO ANTONIO DO ICA
                  ibge_code: '1303700'
                - name: SAO GABRIEL DA CACHOEIRA
                  ibge_code: '1303809'
                - name: SAO PAULO DE OLIVENCA
                  ibge_code: '1303908'
                - name: SAO SEBASTIAO DO UATUMA
                  ibge_code: '1303957'
                - name: SILVES
                  ibge_code: '1304005'
                - name: TABATINGA
                  ibge_code: '1304062'
                - name: TAPAUA
                  ibge_code: '1304104'
                - name: TEFE
                  ibge_code: '1304203'
                - name: TONANTINS
                  ibge_code: '1304237'
                - name: UARINI
                  ibge_code: '1304260'
                - name: URUCARA
                  ibge_code: '1304302'
                - name: URUCURITUBA
                  ibge_code: '1304401'
        '400':
          description: Invalid request error
          content:
            application/json:
              schema:
                type: string
                example:
                  error: An error ocurred during request to external API to get info about SP
        '422':
          description: Invalid parameters
          content:
            application/json:
              schema:
                type: string
                example:
                  error:
                    code:
                      - The county code informed is not valid, Allowed values are: [AL,AP,AM,BA,CE,DF,ES,GO,MA,MT,MS,MG,PA,PB,PR,PE,PI,RJ,RN,RS,RO,RR,SC,SP,SE,TO]
      deprecated: false
